services:
  config-server:
    image: config-service
    build:
      context: ./config-service
    healthcheck:
      test: 'exit 0'
    ports:
      - '10000:10000'
    networks:
      - 'jaguilcu-network'
  registry-server:
    image: registry-service
    build:
      context: ./registry-service
    healthcheck:
      test: 'exit 0'
    ports:
      - '10002:10002'
    networks:
      - 'jaguilcu-network'
    depends_on:
      config-server:
        condition: service_healthy
  gateway-server:
    image: gateway-service
    build:
      context: ./gateway-service
    healthcheck:
      test: 'exit 0'
    ports:
      - '8080:8080'
    networks:
      - 'jaguilcu-network'
    depends_on:
      config-server:
        condition: service_healthy
      registry-server:
        condition: service_healthy
  products:
    image: ms-products
    build:
      context: ./products
    ports:
      - '5050:5050'
    networks:
      - 'jaguilcu-network'
    depends_on:
      config-server:
        condition: service_healthy
      registry-server:
        condition: service_healthy
      gateway-server:
        condition: service_healthy
  customers:
    image: ms-customers
    build:
      context: ./customers
    ports:
      - '5051:5051'
    networks:
      - 'jaguilcu-network'
    depends_on:
      config-server:
        condition: service_healthy
      registry-server:
        condition: service_healthy
      gateway-server:
        condition: service_healthy
  transactions:
    image: ms-transactions
    build:
      context: ./transactions
    ports:
      - '5052:5052'
    networks:
      - 'jaguilcu-network'
    depends_on:
      config-server:
        condition: service_healthy
      registry-server:
        condition: service_healthy
      gateway-server:
        condition: service_healthy
networks:
 jaguilcu-network: