services:
  config-server:
    image: config-service
    build:
      context: ./config-service
      dockerfile: Dockerfile
    #restart: 'no'
    #container_name: config-service
    ports:
      - '10000:10000'
    networks:
      - 'jaguilcu-network'
  registry-server:
    image: registry-server
    build:
      context: ./registry-service
      dockerfile: Dockerfile
    #restart: 'no'
    #container_name: config-service
    ports:
      - '10002:10002'
    networks:
      - 'jaguilcu-network'
  gateway-server:
    image: gateway-service
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    #restart: 'no'
    #container_name: config-service
    ports:
      - '8080:8080'
    networks:
      - 'jaguilcu-network'
networks:
 jaguilcu-network: