services:
  config-server:
    image: config-service
    restart: always
    container_name: config-service
    ports:
      - '10000:10000'
    networks:
      - 'jaguilcu-network'
  registry-server:
    image: registry-service
    restart: always
    container_name: registry-service
    ports:
     - '10002:10002'
    networks:
     - 'jaguilcu-network'
networks:
 jaguilcu-network: