server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  data:
    mongodb:
      database: bootcampdb
      uri: mongodb+srv://jaguilcu:cmaZzUpkJXvZPttO@bootcampdb.gd4uo.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
      auto-index-creation: true
eureka:
  client:
    serviceUrl:
      defaultZone: 'http://registry-server:10002/eureka/'
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}

resilience4j.circuitbreaker:
  instances:
    customerService:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 4
      waitDurationInOpenState: 2s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10