server:
  port: 10000

spring: 
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/jaguilar-developer/bootCamp-S2
          search-paths: config-files