server:
  port: 10001
spring: 
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/jaguilar-developer/bootCamp-S2
          search-paths: config-files
  application:
    name: bank-nttdata-service